"""Updated Message model with proper timestamps

Revision ID: f37438495888
Revises: 91bccc19e801
Create Date: 2024-10-29 23:24:43.703906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f37438495888'
down_revision = '91bccc19e801'
branch_labels = None
depends_on = None


def upgrade():
    # Create a new table with the desired structure
    op.create_table('messages_new',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('body', sa.String(), nullable=False),
        sa.Column('username', sa.String(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), onupdate=sa.func.now(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )

    # Copy data from the old table to the new table
    op.execute("""
        INSERT INTO messages_new (id, body, username, created_at, updated_at)
        SELECT id, body, username, created_at, updated_at FROM messages
    """)

    # Drop the old table
    op.drop_table('messages')

    # Rename the new table to the old table's name
    op.rename_table('messages_new', 'messages')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('messages', 'body',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
